### ISSUE TITLE
Grundgerüst + Verknüpfungen

### ISSUE THREAD

**Issue by SzabiSch** [coding-bootcamps-eu/book-a-barber#4]
- [x] Branches für Features erstellen
- [x] Grundgerüst mit 4 Routes erstellen
- [x] Verknüpfungen einrichten 
- [x] Buttons erstellen für Navigation

**Comment by EmreTy** [comment]
👏👏👏

**Comment by SzabiSch** [comment]
1. Aufgabe erledigt ✅
